apiVersion: projectcalico.org/v3
kind: GlobalThreatFeed
metadata:
  name: malicious-ipfeed
spec:
  pull:
    http:
      url: https://raw.githubusercontent.com/ejrv/VPNs/master/vpn-ipv4.txt
  globalNetworkSet:
    labels:
      feed: ejr-vpn
